export enum Screens {
	Default = 0,
	ClubInfo = 1,
	ClubList = 2,
	TrainingBase = 3,
	FighterList = 4,
	FighterProfile = 5,
	Recruit = 6,
	Transfer = 7,
	Inventory = 8,
	Shop = 9,
	Market = 10,
	Repair = 11,
	CombatList = 12,
	CombatFriendly = 13,
	Championship = 14,
	Messages = 15,
	Chat = 16,
	PremiumShop = 17,
	Summary = 18,
	ShopTabs = 19,
	Teams = 20,
}
